name: building_blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "Hello, World!"

    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: successful  step
              run: |
                echo "I will succeed !"
                exit 0
            - name: echo-goodbye
              run: echo "Goodbye, World!"
              