name: workflow_events

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master
    # schedule:
    #     - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo "I 've traggard by a ${{github.event_name}}!"

   
